//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-connectToDB-SSD_SERVICE_ID_sd_bpnyOX6cbRmRVkRN
import { connectToDB as SSD_SERVICE_ID_sd_bpnyOX6cbRmRVkRN } from './sd-services/connectToDB';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-connectToDB-SSD_SERVICE_ID_sd_bpnyOX6cbRmRVkRN
SSD_SERVICE_ID_sd_bpnyOX6cbRmRVkRN,
];
